### ISSUE TITLE
When using an address which is not prefixed with xch Address does not decode correctly

### ISSUE THREAD

**Issue by darkverbito** [Rigidity/chia-utils#1]
While testing against arbor-wallet-website configured against testnet10, it became apparent that the only prefix supported by Address was one that was prefixed by xch.

The following configuration of blockchain.json allows the website to start:

```
{
    "~/.chia/testnet10": {
        "name": "Chia TestNet10",
        "unit": "Mojo",
        "logo": "/icons/blockchains/chia.png",
        "agg_sig_me_extra_data": "ae83525ba8d1dd3f09b277de18ca3e43fc0af20d20c4b3e92ef2a48bd291ccb2",
        "ticker": "txch",
        "precision": 12,
        "blockchain_fee": 0
    }
}
```

However any call to the server such as:
```
curl -s http://localhost/api/v2/balance -H "Content-Type: application/json" -X POST -d '{"address": "txch16czdlptr2k9x0jydhxsludpuhew34lruktqlumwpq2m72rueqyzqfyakag"}'
```
Results in an error because a prefix of txch is not supported correctly:
```
[2022-01-06T16:38:53.183Z] - error: Error: Invalid checksum for txch16czdlptr2k9x0jydhxsxudpuhew34lruktqlumwpq2m72rueqyzqfyakag
    at Object.decode (/Development/chia/arbor-wallet-website/node_modules/bech32/dist/index.js:158:15)
    at new Address (/Development/chia/arbor-wallet-website/node_modules/chia-tools/dist/types/crypto/Address.js:12:41)
        -> /Development/chia/arbor-wallet-website/node_modules/chia-tools/src/types/crypto/Address.ts:11:32
    at /Development/chia/arbor-wallet-website/dist/routes/v2/balance.js:22:25
        -> /Development/chia/arbor-wallet-website/src/routes/v2/balance.ts:15:25
    at Generator.next (<anonymous>)
    at /Development/chia/arbor-wallet-website/dist/routes/v2/balance.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Development/chia/arbor-wallet-website/dist/routes/v2/balance.js:4:12)
    at /Development/chia/arbor-wallet-website/dist/routes/v2/balance.js:15:47
        -> /Development/chia/arbor-wallet-website/src/routes/v2/balance.ts:9:48
    at Layer.handle [as handle_request] (/Development/chia/arbor-wallet-website/node_modules/express/lib/router/layer.js:95:5)
    at next (/Development/chia/arbor-wallet-website/node_modules/express/lib/router/route.js:137:13)
```
Changing the above configuration of blockchain.json allows the call to succeed:
```
{
    "~/.chia/testnet10": {
        "name": "Chia TestNet10",
        "unit": "Mojo",
        "logo": "/icons/blockchains/chia.png",
        "agg_sig_me_extra_data": "ae83525ba8d1dd3f09b277de18ca3e43fc0af20d20c4b3e92ef2a48bd291ccb2",
        "ticker": "xch",
        "precision": 12,
        "blockchain_fee": 0
    }
}
```
When called (inappropriately) like this:
```
curl -s http://localhost/api/v2/balance -H "Content-Type: application/json" -X POST -d '{"address": "xch16czdlptr2k9x0jydhxsludpuhew34lruktqlumwpq2m72rueqyzqfyakag"}'

[2022-01-06T16:50:02.324Z] - info: HTTP 200 POST 28ms /api/v2/balance {}
{"balance":1000000000000}
```

**Comment by Rigidity** [comment]
If the address was originally from a Chia wallet, you cannot simply change xch to txch, as the part after the prefix changes depending on which prefix you used. You must have an actual txch address to begin with. Where did you generate it?

**Comment by darkverbito** [comment]
I set up the arbor wallet backend using a configuration of blockchain then directly called into the API using CURL. I put all these details into the original bug submission. Essentially arbor-wallet-website cannot support a testnet with a proper prefix because of the bug here.

**Comment by Rigidity** [comment]
The "invalid checksum" error message can occur when a bech32 address is found instead of specifically bech32m (what Chia uses). Did you generate the address with the API?
